FROM python:3.8.5-alpine3.12
RUN apk add postgresql-dev postgresql-libs gcc musl-dev
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE 3000
COPY . /usr/src/app/other_app
WORKDIR /usr/src/app/other_app
RUN pip install -r requirements.txt
CMD ["flask","run","--host=0.0.0.0","-p","3000"]
